import * as React from 'react';
import { NextPage } from 'next';
import Head from 'next/head';
import Box from '@mui/material/Box';
import CssBaseline from '@mui/material/CssBaseline';
import Footer from '../components/Footer';
import Header from '../components/Header';
import SearchBar from '../components/SearchBar';
import FriendList from '../components/FriendList';
import { SelectFriendContext } from '../contexts/FriendContext';
import ChatContent from '../components/ChatContent';



const Home: NextPage = () => {
    const [selectedFriend, setSelectedFriend] = React.useState(null);
    const selectFriend = (user: any) => {
        setSelectedFriend(user);
    };

    return (    
        <SelectFriendContext.Provider value={{user: selectedFriend, selectFriend}} >
            <Head>
                <title>Piggies Chat</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <CssBaseline />
            <Box
                sx = {{
                    display: 'flex'
                }}
            >
                <Box
                    sx = {{
                        width: {xs: '100%', sm: 420},
                    }}
                >
                    <Header />
                    <SearchBar />
                    <FriendList />
                </Box>
                <ChatContent/>
            </Box>
            <Footer />
        </SelectFriendContext.Provider>
    )
}

export default Home;